name: sway-yambar
summary: Sway WM with Yambar panel
description: |
  This snap requires access to the system logind. (as a root user):  
  `snap connect sway-yambar:login-session-control`  
  `snap connect sway-yambar:login-session-observe`

  Also to fix Firefox crashes it's currently needed:  
  `snap connect firefox:wayland sway-yambar`

  Then start Sway in a free tty as a non-privileged user:  
  `export WAYLAND_DISPLAY=wayland-1`  
  `systemctl --user import-environment WAYLAND_DISPLAY`  
  `exec sway-yambar`

  HOME directory of this snap is /home/$USER/snap/sway-yambar/common/  
  Default configs can be obtained from /snap/sway-yambar/current/etc/  
  Launching a `foot-terminal` snap using $mod+Enter hotkey is supported out of the box.
source-code: https://github.com/iomezk/snap-sway-yambar
license: MIT
confinement: strict
base: core22

apps:
  sway-yambar:
    command-chain:
    - sway-wrapper
    command: bin/sway
    slots:
    - wayland
    plugs:
    - desktop  # xdg-open
    - login-session-control
    - login-session-observe
    - opengl
  swaymsg:
    command: bin/swaymsg

environment:
  HOME: $SNAP_USER_COMMON
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/.config
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/lib
  XKB_CONFIG_ROOT: $SNAP/gui-lib/usr/share/X11/xkb
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gui-lib/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  MESA_SHADER_CACHE_DISABLE: "true"
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
  WLR_BACKENDS: libinput,drm
  SWAYSOCK: $XDG_RUNTIME_DIR/sway-ipc.$WAYLAND_DISPLAY.sock
  WAYLAND_DISPLAY: ../$WAYLAND_DISPLAY

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

layout:
  /etc/sway/config:
    symlink: $SNAP/etc/sway/config
  /etc/yambar/config.yml:
    symlink: $SNAP/etc/yambar/config.yml
  /usr/share/libinput:
    symlink: $SNAP/gui-lib/usr/share/libinput
  /usr/share/libwacom:
    symlink: $SNAP/gui-lib/usr/share/libwacom
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts
  /usr/share/font2:
    symlink: $SNAP/fonts

adopt-info: sway
parts:
  deps:
    build-snaps:
    - gnome-42-2204-sdk
    plugin: nil
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  libseat:
    after:
    - deps
    source: https://git.sr.ht/~kennylevinsen/seatd/archive/0.8.0.tar.gz
    source-checksum: sha256/a562a44ee33ccb20954a1c1ec9a90ecb2db7a07ad6b18d0ac904328efbcf65a0
    source-type: tar
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/libseat-system-libsystemd.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/libseat-apparmor-flood.patch"
    build-environment: &buildenv
    - PATH: /snap/gnome-42-2204-sdk/current/usr/bin${PATH:+:$PATH}
    - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    - PKG_CONFIG_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/usr
    - --libdir=lib
    - -Ddefault_library=static
    - -Dlibseat-logind=systemd
    - -Dlibseat-seatd=disabled
    - -Dserver=disabled
    - -Dman-pages=disabled
    prime:
    - -*
  wlroots:
    after:
    - deps
    - libseat
    source: https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/0.16.2/wlroots-0.16.2.tar.gz
    source-checksum: sha256/f502959db8bc029e32f10a837b37257bb8c5ed269bceddf9492f0bb381bebf76
    source-type: tar
    build-packages:
    - hwdata
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/wlroots-noshm.patch"
    build-environment: *buildenv
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/usr
    - --libdir=lib
    - -Ddefault_library=static
    - -Dexamples=false
    - -Dbackends=drm,libinput
    prime:
    - -*
  sway:
    after:
    - deps
    - wlroots
    source: https://github.com/swaywm/sway/archive/1.8.1.tar.gz
    source-checksum: sha256/e9f575761342fc8fe0cfeea80c90f32ddfa8c543572fec179f40922346f47dff
    source-type: tar
    build-packages:
    - jq
    - libevdev-dev
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-noshm.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-use-wayland-display-env.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-yambar.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-config.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-apparmor-flood.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/sway-enum-fix.patch"
    build-environment: *buildenv
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    - -Ddefault-wallpaper=false
    - -Dzsh-completions=false
    - -Dbash-completions=false
    - -Dfish-completions=false
    - -Dswaybar=false
    - -Dman-pages=disabled
    override-build: |
      craftctl default
      craftctl set "version=$(jq -r .version meson-info/intro-projectinfo.json)"
    prime:
    - bin
    - etc
  yambar:
    after:
    - deps
    source: https://codeberg.org/dnkl/yambar/archive/1.10.0.tar.gz
    source-checksum: sha256/3c53d6fc245707d6ff6174395b03d7f069a48da9fb63b612c82d706c1c09b193
    source-type: tar
    build-packages:
    - bison
    - libyaml-dev
    - flex
    - scdoc
    - git  # for latest libtllist-dev
    # plugins:
    - libmpdclient-dev
    - libjson-c-dev
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/yambar-systemwide-config.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/yambar-string-particle-truncation-rewrite.patch"
    build-environment: *buildenv
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    - -Dbackend-x11=disabled
    - -Dcore-plugins-as-shared-libraries=true
    - -Dplugin-dwl=disabled
    - -Dplugin-river=disabled
    - -Dplugin-backlight=enabled
    - -Dplugin-battery=enabled
    - -Dplugin-mpd=enabled
    - -Dplugin-i3=enabled
    - -Dplugin-pulse=enabled
    - -Dplugin-removables=enabled
    - -Dplugin-sway-xkb=enabled
    stage-packages:
    - libmpdclient2
    organize:
      '**/*.so*': lib/
    prime:
    - bin
    - lib
  font-awesome:
    source: https://github.com/FortAwesome/Font-Awesome/archive/6.4.0.tar.gz
    source-checksum: sha256/c8d286b1941fca9841d07fe165f9e0a5ee1ccf99417cf60025986f303b54da5c
    source-type: tar
    plugin: dump
    organize:
      webfonts/*0.ttf: fonts/
    prime:
    - fonts/
