name: sway-yambar
version: '1.7-core22'
summary: Sway WM with Yambar panel
description: |
  This snap requires access to the system logind. (as a root user):  
  `snap connect sway-yambar:login-session-control`  
  `snap connect sway-yambar:login-session-observe`

  Also to fix Firefox crashes it's currently needed:  
  `snap connect firefox:wayland sway-yambar`

  Then start Sway in a free tty as a non-privileged user:  
  `exec sway-yambar`

  HOME directory of this snap is /home/᚜user᚛/snap/sway-yambar/common/  
  Default configs can be obtained from /snap/sway-yambar/current/etc/
source-code: https://github.com/iomezk/snap-sway-yambar
license: MIT
confinement: strict
base: core22

apps:
  sway-yambar:
    command-chain:
    - sway-wrapper
    command: bin/sway
    slots:
    - wayland
    plugs:
    - login-session-control
    - login-session-observe
    - opengl
#    - seatd
  swaymsg:
    command: bin/swaymsg

environment:
  HOME: $SNAP_USER_COMMON
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/.config
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET/yambar
  XKB_CONFIG_ROOT: $SNAP/gui-lib/usr/share/X11/xkb
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gui-lib/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib
#  seatd:
#    interface: system-files
#    write:
#    - /run/seatd.sock

layout:
  /etc/sway/config:
    symlink: $SNAP/etc/sway-config
  /etc/yambar/config.yml:
    symlink: $SNAP/etc/yambar-config.yml
  /usr/share/libinput:
    symlink: $SNAP/gui-lib/usr/share/libinput
  /usr/share/libwacom:
    symlink: $SNAP/gui-lib/usr/share/libwacom
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts
  /usr/share/font2:
    symlink: $SNAP/share/fonts

parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  libseat:
    source: https://git.sr.ht/~kennylevinsen/seatd/archive/0.7.0.tar.gz
    source-checksum: sha256/210ddf8efa1149cde4dd35908bef8e9e63c2edaa0cdb5435f2e6db277fafff3c
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/
    - -Dlibseat-logind=systemd
    - -Dlibseat-seatd=disabled
    - -Dserver=disabled
    - -Dman-pages=disabled
    build-packages:
    - meson
    - ninja-build
    - libsystemd-dev
    prime:
    - '**/*.so*'
  wlroots:
    after:
    - local
    - libseat
    source: https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/0.15.1/wlroots-0.15.1.tar.gz
    source-checksum: sha256/5b92f11a52d978919ed1306e0d54c9d59f1762b28d44f0a2da3ef3b351305373
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/
    - -Dexamples=false
    - -Dbackends=drm,libinput
    override-pull: |
      craftctl default
      patch -p1 -i ../../local/src/patches/wlroots-noshm.patch
    override-build: |
      craftctl default
      ninja -C "$CRAFT_PART_BUILD" install
    build-packages:
    - meson
    - ninja-build
    - libwayland-dev
    - wayland-protocols
    - libdrm-dev
    - libgbm-dev
    - libxkbcommon-dev
    prime:
    - '**/*.so*'
  sway:
    after:
    - local
    - wlroots
    source: https://github.com/swaywm/sway/archive/1.7.tar.gz
    source-checksum: sha256/0c64536fb2883ec518e75cfb119f9300115fb49b084e3fde62b794fe2c6c8d84
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/
    - -Ddefault-wallpaper=false
    - -Dzsh-completions=false
    - -Dbash-completions=false
    - -Dfish-completions=false
    - -Dswaybar=false
    - -Dman-pages=disabled
    override-pull: |
      craftctl default
      patch -p1 -i ../../local/src/patches/sway-parent-runtime-dir.patch
      patch -p1 -i ../../local/src/patches/sway-yambar.patch
    build-packages:
    - meson
    - ninja-build
    - libcairo2-dev
    - libpango1.0-dev
    - libgles-dev
    - libevdev-dev
    - libinput-dev
    prime:
    - bin
  yambar:
    after:
    - local
    source: https://codeberg.org/dnkl/yambar/archive/1.9.0.tar.gz
    source-checksum: sha256/46f3002338f451c154678167bf3d5f593307954b6f381c50ddef2726b1a8c811
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/
    - -Dbuildtype=release
    - -Dbackend-x11=disabled
    - -Dcore-plugins-as-shared-libraries=true
    - -Dplugin-dwl=disabled
    - -Dplugin-river=disabled
    - -Dplugin-backlight=enabled
    - -Dplugin-battery=enabled
    - -Dplugin-mpd=enabled
    - -Dplugin-i3=enabled
    - -Dplugin-pulse=enabled
    - -Dplugin-removables=enabled
    - -Dplugin-sway-xkb=enabled
    override-pull: |
      craftctl default
      patch -p1 -i ../../local/src/patches/yambar-systemwide-config.patch
    build-packages:
    - meson
    - ninja-build
    - bison
    - libpixman-1-dev
    - libyaml-dev
    - libfontconfig1-dev
    - libwayland-dev
    - wayland-protocols
    - flex
    - scdoc
    # plugins:
    - libudev-dev
    - libmpdclient-dev
    - libjson-c-dev
    - libpulse-dev
    stage-packages:
    - libmpdclient2
    organize:
      usr/lib/: lib/
    prime:
    - bin
    - '**/*.so*'
  font-awesome:
    source: https://github.com/FortAwesome/Font-Awesome/archive/6.4.0.tar.gz
    source-checksum: sha256/c8d286b1941fca9841d07fe165f9e0a5ee1ccf99417cf60025986f303b54da5c
    source-type: tar
    plugin: dump
    organize:
      webfonts/*0.ttf: share/fonts/
    prime:
    - share/
