name: sway-yambar
version: '1.7-core22'
summary: sway with yambar panel
description: ' '
grade: stable
confinement: strict
base: core22

apps:
  sway:
    command-chain:
    - bin/sway
    command: usr/bin/sway
    plugs:
    - opengl
    - wayland
  yambar:
    command-chain:
    - bin/sway
    command: usr/bin/yambar
    plugs:
    - opengl
    - wayland

environment:
  HOME: $SNAP_USER_COMMON
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/.config
#  SNAP_RUNTIME_DIR: $XDG_RUNTIME_DIR
  PATH: $SNAP/usr/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/yambar
  XKB_CONFIG_ROOT: $SNAP/gui-lib/usr/share/X11/xkb
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gui-lib/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: $SNAP/gui-lib

layout:
  /usr/share/libinput:
    symlink: $SNAP/gui-lib/usr/share/libinput
  /usr/share/libwacom:
    symlink: $SNAP/gui-lib/usr/share/libwacom
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts
  /usr/share/font2:
    symlink: $SNAP/usr/share/fonts

parts:
  sway:
    source: https://github.com/swaywm/sway/archive/1.7.tar.gz
    source-checksum: sha256/0c64536fb2883ec518e75cfb119f9300115fb49b084e3fde62b794fe2c6c8d84
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/usr
    - -Ddefault-wallpaper=false
    - -Dzsh-completions=false
    - -Dbash-completions=false
    - -Dfish-completions=false
    - -Dswaybar=false
    - -Dman-pages=disabled
    build-packages:
    - meson
    - ninja-build
    - libwlroots-dev
    - libcairo2-dev
    - libpango1.0-dev
    stage-packages:
    - libwlroots10
  yambar:
    source: https://codeberg.org/dnkl/yambar.git
    source-type: git
    plugin: meson
    meson-parameters:
    - -Dprefix=/usr
    - -Dbuildtype=release
    - -Dbackend-x11=disabled
    - -Dcore-plugins-as-shared-libraries=true
    - -Dplugin-dwl=disabled
    - -Dplugin-river=disabled
    - -Dplugin-backlight=enabled
    - -Dplugin-battery=enabled
    - -Dplugin-mpd=enabled
    - -Dplugin-i3=enabled
    - -Dplugin-pulse=enabled
    - -Dplugin-removables=enabled
    - -Dplugin-sway-xkb=enabled
    build-packages:
    - meson
    - ninja-build
    - bison
    - libpixman-1-dev
    - libyaml-dev
    - libfontconfig1-dev
    - libwayland-dev
    - wayland-protocols
    - flex
    - scdoc
    # plugins:
    - libudev-dev
    - libmpdclient-dev
    - libjson-c-dev
    - libpulse-dev
    stage-packages:
    - libmpdclient2
    prime:
    - -usr/include
    - -usr/share
  font-awesome:
    source: https://github.com/FortAwesome/Font-Awesome/archive/6.4.0.tar.gz
    source-checksum: sha256/c8d286b1941fca9841d07fe165f9e0a5ee1ccf99417cf60025986f303b54da5c
    source-type: tar
    plugin: dump
    organize:
      webfonts/*0.ttf: usr/share/fonts/
    prime:
    - usr/
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    organize:
      sway: bin/
      fonts.conf: etc/fonts/
